name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        deno: [v1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Test
        run: deno task coverage
        env:
          SMTP_TEST_USERNAME: ${{ secrets.SMTP_TEST_USERNAME }}
          SMTP_TEST_PASSWORD: ${{ secrets.SMTP_TEST_PASSWORD }}
          SMTP_TEST_FROM_EMAIL: ${{ secrets.SMTP_TEST_FROM_EMAIL }}
          SMTP_TEST_TO_EMAIL: ${{ secrets.SMTP_TEST_TO_EMAIL }}

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: ./dist/coverage/lcov.info
